package com.messmanagement.menu.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.DayOfWeek; // Using java.time.DayOfWeek
import java.time.LocalDate;

@Entity
@Table(name = "weekly_menu_config", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"day_of_week", "meal_type", "item_id", "effective_date_start"})
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class WeeklyMenuConfig {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "menu_config_id")
    private Long menuConfigId;

    @Enumerated(EnumType.STRING)
    @Column(name = "day_of_week", nullable = false, length = 10) // Length for "WEDNESDAY"
    private DayOfWeek dayOfWeek; // From java.time package

    @Enumerated(EnumType.STRING)
    @Column(name = "meal_type", nullable = false, length = 20) // Length for "BREAKFAST"
    private MealType mealType;

    @ManyToOne(fetch = FetchType.LAZY) // Many WeeklyMenuConfig entries can point to one MenuItem
    @JoinColumn(name = "item_id", nullable = false)
    private MenuItem menuItem; // Reference to the MenuItem entity

    @Column(name = "effective_date_start", nullable = false)
    private LocalDate effectiveDateStart; // Date from which this config is valid [cite: 43]

    @Column(name = "effective_date_end")
    private LocalDate effectiveDateEnd; // Date until which this config is valid (nullable) [cite: 44]

    // Constructors, Getters, Setters will be generated by Lombok
}