package com.messmanagement.subscription.dto;

import lombok.Data;

@Data
public class SubscriptionPurchaseRequestDTO {
    // For now, this DTO might be simple.
    // If using Stripe Payment Elements on the client, this DTO might carry a 'paymentMethodId'.
    // If using Stripe Checkout Sessions created by the backend, this DTO might be empty
    // or carry some plan identifier if there were multiple plans.
    // For a single Rs. 3500 monthly plan, it might not need much.

    // private String paymentMethodId; // Example if not using Stripe Checkout sessions generated by backend
    private String planId = "MONTHLY_MESS_SUBSCRIPTION_RS3500"; // Example, could be fixed in service
}